### ISSUE TITLE
Error 1.8

### ISSUE THREAD

**Issue by ale2017** [NyaaCat/RPGitems-reloaded#209]
[14:06:50 WARN]: [RPGItems] Task #22 for RPGItems v3.5.143 generated an exception
java.lang.NoSuchMethodError: org.bukkit.inventory.PlayerInventory.getItemInMainHand()Lorg/bukkit/inventory/ItemStack;
        at think.rpgitems.power.PowerTicker.run(PowerTicker.java:22) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]

Fix please
Gracias

**Comment by Librazy** [comment]
RPGItems [v3.5.**143**](https://github.com/NyaaCat/RPGitems-reloaded/releases/tag/1.10-v3.5.143) is for 1.10 and uses some newer API like getItemInMainHand. 
Check out builds on branch 1.8 like [v3.5.**149**](https://github.com/NyaaCat/RPGitems-reloaded/releases/tag/1.8-v3.5.149)
